export const chapter1Data = {
  name: "Chapter 1: Number System",
  questions: [
    {
      question:
        "If 'a' and 'b' are real numbers then a + b is a real no. This law is called",
      options: {
        a: "Closure law",
        b: "commutative law",
        c: "associative law",
        d: "Distributive law",
      },
      answer: "a",
      category: "Real Number Closure",
    },
    {
      question: "If a ∈ R then multiplicative inverse of a is",
      options: {
        a: "0",
        b: "\\frac{1}{a}",
        c: "a",
        d: "-a",
      },
      answer: "b",
      category: "Multiplicative Inverse",
    },
    {
      question: "Which of the following is field?",
      options: {
        a: "Q",
        b: "N",
        c: "W",
        d: "Q'",
      },
      answer: "a",
      category: "Number Field Identification",
    },
    {
      question: "1>−1−3 >-5, this property is called",
      options: {
        a: "Additive property",
        b: "transitive property",
        c: "multiplicative property",
        d: "closure property",
      },
      answer: "b",
      category: "Inequality Transitivity",
    },
    {
      question: "Let a,b,c,d ∈ R then a=b and c=d⇒",
      options: {
        a: "a+b=c+d",
        b: "a-b=c+d",
        c: "a+c=b+d",
        d: "a.b=c.d",
      },
      answer: "a",
      category: "Equality Properties",
    },
    {
      question: "If Z₁ = (x₁, y₁), Z₂ = (x₂,y₂) where Z₁, Z₂ ∈ C then Z₁+Z₂=?",
      options: {
        a: "(x₁+x₂, y₁+y₂)",
        b: "(x₁+y₂, x₂+y₁)",
        c: "(x₁+y₁, x₂+y₂)",
        d: "(x₁-x₂, y₁-y₂)",
      },
      answer: "a",
      category: "Complex Number Addition",
    },
    {
      question: "If Z₁ = 3-6i and Z₂=4+5i then Z₁Z₂=?",
      options: {
        a: "42-9i",
        b: "42-9i",
        c: "42+9i",
        d: "4+i",
      },
      answer: "c",
      category: "Complex Number Multiplication",
    },
    {
      question: "If Z₁ = (1, 0), Z₂ = (2, 3) then Z₁Z₂=?",
      options: {
        a: "-2+3i",
        b: "2-3i",
        c: "2+3i",
        d: "-2-3i",
      },
      answer: "b",
      category: "Complex Number Multiplication",
    },
    {
      question: "(3,5) + (0, 4) =?",
      options: {
        a: "(3, 5)",
        b: "(0, 9)",
        c: "(0, 4)",
        d: "(3, 9)",
      },
      answer: "d",
      category: "Complex Number Addition",
    },
    {
      question: "Additive inverse of (3,3) in C is",
      options: {
        a: "(3, 0)",
        b: "(0, 3)",
        c: "(-3, 3)",
        d: "(-3, -3)",
      },
      answer: "d",
      category: "Complex Additive Inverse",
    },
    {
      question: "If Z =(a,b) then multiplicative inverse of Z is",
      options: {
        a: "\\frac{a}{a^2+b^2}, \\frac{b}{a^2+b^2}",
        b: "\\frac{a}{a^2+b^2}, \\frac{-b}{a^2+b^2}",
        c: "\\frac{-a}{a^2+b^2}, \\frac{-b}{a^2+b^2}",
        d: "\\frac{-a}{a^2+b^2}, \\frac{b}{a^2+b^2}",
      },
      answer: "b",
      category: "Complex Multiplicative Inverse",
    },
    {
      question: "If Z = a+b then |Z|=?",
      options: {
        a: "a+b",
        b: "\\sqrt{a^2+b^2}",
        c: "a²+b²",
        d: "a²+b²+2ab",
      },
      answer: "b",
      category: "Complex Modulus",
    },
    {
      question: "If Z = a+b, then \\(\\bar{Z}\\) = ?",
      options: {
        a: "a-b",
        b: "-(a+b)",
        c: "-a+b",
        d: "a+b",
      },
      answer: "a",
      category: "Complex Conjugate",
    },
    {
      question: "i¹⁵ =?",
      options: {
        a: "1",
        b: "-i",
        c: "i",
        d: "-1",
      },
      answer: "b",
      category: "Powers of i",
    },
    {
      question: "The value of i²⁵ =?",
      options: {
        a: "i",
        b: "-i",
        c: "1",
        d: "-1",
      },
      answer: "b",
      category: "Powers of i",
    },
    {
      question: "Conjugate of (-3, 4) is",
      options: {
        a: "(3,4)",
        b: "(3,-4)",
        c: "(-3,-4)",
        d: "(-3,4)",
      },
      answer: "b",
      category: "Complex Conjugate",
    },
    {
      question: "(-1)³¹ = ?",
      options: {
        a: "i",
        b: "-i",
        c: "1",
        d: "-1",
      },
      answer: "b",
      category: "Powers of i",
    },
    {
      question: "The multiplicative inverse of 1-3i is",
      options: {
        a: "3i",
        b: "\\frac{1}{1-3i}",
        c: "-\\frac{1}{3}",
        d: "none",
      },
      answer: "b",
      category: "Complex Mult Inverse",
    },
    {
      question: "The value of i⁻²⁹ is",
      options: {
        a: "i",
        b: "-i",
        c: "1",
        d: "-1",
      },
      answer: "b",
      category: "Powers of i",
    },
    {
      question: "If Z∈ C then Z.\\(\\bar{Z}\\) =?",
      options: {
        a: "Z",
        b: "Z¹",
        c: "Z²",
        d: "|Z|²",
      },
      answer: "d",
      category: "Complex Modulus",
    },
    {
      question: "If Z₁, Z₂ ∈ C then Z₁ + Z₂ = ?",
      options: {
        a: "Z₁+Z₂",
        b: "Z₁-Z₂",
        c: "\\bar{Z₁}+\\bar{Z₂}",
        d: "\\bar{Z₁}-\\bar{Z₂}",
      },
      answer: "a",
      category: "Complex Number Addition",
    },
    {
      question: "The value of (3+2i)³ is",
      options: {
        a: "62+9i",
        b: "46-9i",
        c: "46i-9",
        d: "46i+9",
      },
      answer: "b",
      category: "Complex Number Power",
    },
    {
      question: "C has no identity with respect to + other than",
      options: {
        a: "1+0i",
        b: "0+1i",
        c: "0+0i",
        d: "1+1i",
      },
      answer: "c",
      category: "Complex Additive Identity",
    },
    {
      question: "The conjugate of \\(\\frac{2+3i}{1+i}\\) =?",
      options: {
        a: "\\frac{2-3i}{1-i}",
        b: "\\frac{2-3i}{1-i}",
        c: "\\frac{2+3i}{1+i}",
        d: "\\frac{2+3i}{-1-i}",
      },
      answer: "a",
      category: "Complex Conjugate",
    },
    {
      question: "(-1+\\sqrt{-3})+(-1-\\sqrt{-3}) = ?",
      options: {
        a: "-2",
        b: "4",
        c: "-4",
        d: "16\\omega",
      },
      answer: "a",
      category: "Complex Number Addition",
    },
    {
      question:
        'The smallest positive integer "k" for which \\(((\\frac{1+i}{1-i}))^k = 1\\) is;',
      options: {
        a: "2",
        b: "4",
        c: "8",
        d: "16",
      },
      answer: "b",
      category: "Complex Number Power",
    },
    {
      question: "Set of even prime natural numbers is;",
      options: {
        a: "Finite",
        b: "Empty",
        c: "Singleton",
        d: "Infinite",
      },
      answer: "c",
      category: "Prime Numbers",
    },
    {
      question:
        "In n is any positive integer then the value of \\(\\frac{i^{4n+1} - i^{4n-1}}{2}\\) = ?",
      options: {
        a: "1",
        b: "-1",
        c: "i",
        d: "-i",
      },
      answer: "c",
      category: "Powers of i",
    },
    {
      question: "\\(\\frac{\\sqrt{18}}{\\sqrt{72}}\\) is;",
      options: {
        a: "Rational number",
        b: "irrational",
        c: "imaginary",
        d: "none of these",
      },
      answer: "a",
      category: "Rational Number Identification",
    },
    {
      question: "2√9 *  √-16 = ?",
      options: {
        a: "24",
        b: "-24",
        c: "48",
        d: "-48",
      },
      answer: "d",
      category: "Complex Number Multiplication",
    },
    {
      question: "\\(\\frac{1+i}{1-i}\\) = ?",
      options: {
        a: "\\sqrt{2}",
        b: "\\frac{1}{\\sqrt{2}}",
        c: "\\frac{3}{\\sqrt{2}}",
        d: "1",
      },
      answer: "c",
      category: "Complex Number Division",
    },
    {
      question: " \\(( \\frac{1-i}{1+i})^{100} = x+iy\\) then;",
      options: {
        a: "x = 2, y = -1",
        b: "x = 1, y = 0",
        c: "x = 0, y = 1",
        d: "x = -1, y = 2",
      },
      answer: "b",
      category: "Complex Number Power",
    },
    {
      question: "{1,-1} is closed with respect to;",
      options: {
        a: "Addition",
        b: "multiplication",
        c: "division",
        d: "both b & c",
      },
      answer: "b",
      category: "Closure Property",
    },
    {
      question: "\\(\\frac{(cos20 + isin20)^3}{(cos30 + isin30)^3}\\) = ?",
      options: {
        a: "cos 20 +i sin 20",
        b: "cos30 +isin 30",
        c: "cos10 +isin10",
        d: "cos20 -isin 20",
      },
      answer: "d",
      category: "Complex Number Division",
    },
    {
      question:
        "The polar coordinates of a point are (2,319°) then the Cartesian coordinates of the point are;",
      options: {
        a: "(1.509,-1.312)",
        b: "(-1.509,-1.312)",
        c: "(1.509,1.312)",
        d: "(-1.509,1.312)",
      },
      answer: "b",
      category: "Polar to Cartesian Conversion",
    },
    {
      question: "The set of rational numbers between two real numbers is",
      options: {
        a: "Finite",
        b: "Empty",
        c: "Infinite",
        d: "Singleton",
      },
      answer: "c",
      category: "Rational Number Density",
    },
    {
      question: "Multiplicative inverse of a non-zero element a ∈ Z is",
      options: {
        a: "\\frac{1}{a}",
        b: "-a",
        c: "1",
        d: "Non-existent",
      },
      answer: "d",
      category: "Multiplicative Inverse",
    },
    {
      question: "The {x ∈ R,x² +10 = 0} is",
      options: {
        a: "{10}",
        b: "{-10}",
        c: "Null set",
        d: "R",
      },
      answer: "c",
      category: "Real Number Solutions",
    },
    {
      question: "Additive identity on N is",
      options: {
        a: "0",
        b: "1",
        c: "No identity",
        d: "None of these",
      },
      answer: "c",
      category: "Additive Identity",
    },
    {
      question: "Additive inverse of 2+√3 is",
      options: {
        a: "2-√3",
        b: "-2+√3",
        c: "-2-√3",
        d: "0",
      },
      answer: "c",
      category: "Additive Inverse",
    },
    {
      question: "The multiplicative inverse of √7 is",
      options: {
        a: "\\frac{1}{\\sqrt{7}}",
        b: "\\sqrt{7}",
        c: "\\frac{1}{7}",
        d: "1",
      },
      answer: "a",
      category: "Multiplicative Inverse",
    },
    {
      question: "0.3575 is",
      options: {
        a: "Rational",
        b: "Irrational",
        c: "Integer",
        d: "Non-recurring decimal.",
      },
      answer: "a",
      category: "Rational Number Identification",
    },
    {
      question: "If |x - 3| < 5, then x lies between:",
      options: {
        a: "-2 and 8",
        b: "-6 and -2",
        c: "-2 and 4",
        d: "-4 and 2",
      },
      answer: "a",
      category: "Inequality Solution",
    },
    {
      question: "x² = is an any no. is +ve",
      options: {
        a: "x²",
        b: "-x²",
        c: "x",
        d: "Both a and b",
      },
      answer: "d",
      category: "Real Number Properties",
    },
    {
      question:
        "If z is a complex number then the minimum value of |z| + |z - 1| is",
      options: {
        a: "1",
        b: "2",
        c: "0",
        d: "-2",
      },
      answer: "a",
      category: "Complex Number Modulus",
    },
    {
      question:
        "If \\(\\frac{Z1}{Z2}\\) is purely imaginary then \\(\\frac{Z1+Z2}{Z1-Z2}\\) = ?",
      options: {
        a: "0",
        b: "1",
        c: "-1",
        d: "Cannot be determine",
      },
      answer: "d",
      category: "Purely Imaginary Condition",
    },
    {
      question: " \\(( \\frac{1 + i\\sqrt{3}}{2})^3 = ?\\)",
      options: {
        a: "\\omega",
        b: "\\omega²",
        c: "1",
        d: "0",
      },
      answer: "c",
      category: "Complex Number Power",
    },
    {
      question: 'If the square of a number x is \\"i\\" then x = ?',
      options: {
        a: "\\frac{1+i}{\\sqrt{2}}",
        b: "\\frac{1-i}{\\sqrt{2}}",
        c: "\\frac{1}{\\sqrt{2}}",
        d: "1 + i",
      },
      answer: "a",
      category: "Complex Square Root",
    },
    {
      question: "If Z = x + iy, then Z² =|Z|² if",
      options: {
        a: "x = 0, y = 0",
        b: "y = 0",
        c: "x ≠ 0, y ≠ 0",
        d: "x = 0, y ≠ 0",
      },
      answer: "b",
      category: "Complex Number Property",
    },
    {
      question: "arg \\(\\frac{z_1}{z_2}\\) = ?",
      options: {
        a: "argz₁ + argz₂",
        b: "argz₁ / argz₂",
        c: "argz₁ - argz₂",
        d: "none of these",
      },
      answer: "c",
      category: "Complex Number Argument",
    },
    {
      question: "The modulus of the complex number 1+itanα = ?",
      options: {
        a: "1",
        b: "tanα",
        c: "secα",
        d: "cosecα",
      },
      answer: "c",
      category: "Complex Number Modulus",
    },
    {
      question:
        "If \\((cos\\theta + isin\\theta)² = x - iy\\) then x² + y² = ?",
      options: {
        a: "1",
        b: "0",
        c: "2",
        d: "-1",
      },
      answer: "a",
      category: "Complex Number Property",
    },
    {
      question: "If z = 4 + 6i² then |z| = ?",
      options: {
        a: "\\sqrt{52}",
        b: "16",
        c: "36",
        d: "2",
      },
      answer: "a",
      category: "Complex Number Modulus",
    },
    {
      question: "If Z = \\(\\frac{2 + 7i}{2 - 8i}\\), then \\(\\bar{Z}\\) = ?",
      options: {
        a: "Z⁻¹",
        b: "\\bar{Z}",
        c: "Z",
        d: "-Z",
      },
      answer: "b",
      category: "Complex Conjugate",
    },
    {
      question: "If Z = cosθ + i sin θ, then 1/z  = ?",
      options: {
        a: "1",
        b: "-1",
        c: "cos θ - i sin θ",
        d: "None of these",
      },
      answer: "c",
      category: "Complex Number Division",
    },
  ],
};
